// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBFaGwYJfylF6azHX6VVStXMDzLNm7JHio',
    appId: '1:935719495705:web:7b3fe35411759b9cb0a288',
    messagingSenderId: '935719495705',
    projectId: 'e-commercialapp-c3fd7',
    authDomain: 'e-commercialapp-c3fd7.firebaseapp.com',
    storageBucket: 'e-commercialapp-c3fd7.firebasestorage.app',
    measurementId: 'G-V7P55QC30K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDv2Z0TL0d5b4FPjWROAJjNeRYFJRcceMA',
    appId: '1:935719495705:android:e0b8ef8498c7f517b0a288',
    messagingSenderId: '935719495705',
    projectId: 'e-commercialapp-c3fd7',
    storageBucket: 'e-commercialapp-c3fd7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCtFARixDLNQJegqh--HA7ZVyd0KoWGd2A',
    appId: '1:935719495705:ios:9e671a7ffac3bce4b0a288',
    messagingSenderId: '935719495705',
    projectId: 'e-commercialapp-c3fd7',
    storageBucket: 'e-commercialapp-c3fd7.firebasestorage.app',
    iosBundleId: 'com.example.eCommerceapp2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCtFARixDLNQJegqh--HA7ZVyd0KoWGd2A',
    appId: '1:935719495705:ios:9e671a7ffac3bce4b0a288',
    messagingSenderId: '935719495705',
    projectId: 'e-commercialapp-c3fd7',
    storageBucket: 'e-commercialapp-c3fd7.firebasestorage.app',
    iosBundleId: 'com.example.eCommerceapp2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBFaGwYJfylF6azHX6VVStXMDzLNm7JHio',
    appId: '1:935719495705:web:69304eef8f855572b0a288',
    messagingSenderId: '935719495705',
    projectId: 'e-commercialapp-c3fd7',
    authDomain: 'e-commercialapp-c3fd7.firebaseapp.com',
    storageBucket: 'e-commercialapp-c3fd7.firebasestorage.app',
    measurementId: 'G-06K377EYC8',
  );
}
